# Generated by Django 4.2.6 on 2023-11-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=10)),
                ('saldo', models.IntegerField()),
                ('dias_mora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('nombre_popriedad', models.CharField(max_length=80)),
                ('num_inmuebles', models.IntegerField()),
                ('años_antiguedad', models.IntegerField()),
                ('saldo_cartera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
                ('num_habitaciones', models.IntegerField()),
                ('area_total_m2', models.IntegerField()),
            ],
        ),
    ]
