# Generated by Django 4.2.6 on 2023-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='num_doc',
            field=models.IntegerField(default=0),
        ),
    ]
