# Generated by Django 4.2.6 on 2023-11-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_num_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='años_antiguedad',
            new_name='anios_antiguedad',
        ),
    ]
